#!/bin/sh
set -e

output=Makefile.qt.am
date="$(date)"
echo "## Generated by qtdeps.sh at $date" > $output
echo "gui_sources =" >> $output
echo "gui_headers =" >> $output
for f in ui/*.ui; do
    i=$(basename $f .ui)
    cat >>$output <<EOF
include/ui_$i.h: \$(srcdir)/ui/$i.ui
	\$(mkdir_p) include
	\$(UIC) \$(srcdir)/ui/$i.ui -o include/ui_$i.h
src/moc_ui_$i.C: include/ui_$i.h
	\$(MOC) include/ui_$i.h -o src/moc_ui_$i.C
src/ui_$i.C: \$(srcdir)/ui/$i.ui
	\$(UIC) -impl ui_$i.h \$(srcdir)/ui/$i.ui -o src/ui_$i.C
gui_sources += src/moc_ui_$i.C src/ui_$i.C
gui_headers += include/ui_$i.h
EXTRA_DIST += ui/$i.ui

EOF
done
cat >>$output <<'EOF'
BUILT_SOURCES = $(gui_sources) $(gui_headers)
## End generated section
EOF
