#!/usr/bin/perl -w
use strict;
use warnings;

# Usage: ls ui/*.ui | qtdeps.pl

my $timestamp = scalar(localtime);
print <<"EOF";
# Generated by $0 at $timestamp
if DO_CLIENT
gui_sources =
gui_headers =
EOF
while (<>)
{
    chomp;
    if (m|^ui/(.*)\.ui$|)
    {
        print <<"EOF";
include/ui_$1.h: \$(srcdir)/ui/$1.ui
\t\$(mkdir_p) include
\t\$(UIC) \$(srcdir)/ui/$1.ui -o include/ui_$1.h
src/moc_ui_$1.C: include/ui_$1.h
\t\$(MOC) include/ui_$1.h -o src/moc_ui_$1.C
src/ui_$1.C: \$(srcdir)/ui/$1.ui
\t\$(UIC) -impl ui_$1.h \$(srcdir)/ui/$1.ui -o src/ui_$1.C
gui_sources += src/moc_ui_$1.C src/ui_$1.C
gui_headers += include/ui_$1.h
EXTRA_DIST += ui/$1.ui

EOF
    }
}
print <<"EOF";
BUILT_SOURCES = \$(gui_sources) \$(gui_headers)
endif
# End generated section
EOF
