version: '2'
services:
  server:
    image: bmerry/abacuscm
    ports:
      - "127.0.0.1:443:8443"
      - "127.0.0.1:7368:7368"
    volumes:
      - "./conf:/conf"
      - "./contest:/contest"
      - "server_data:/data"
      - "./www:/www:ro"
    command: server

  marker:
    image: bmerry/abacuscm
    links:
      - server
    command: marker
    volumes:
      - "./conf:/conf"
      - "marker_data:/data"

volumes:
  server_data: {}
  marker_data: {}
