/**
 * Copyright (c) 2005 - 2006 Kroon Infomation Systems,
 *  with contributions from various authors.
 *
 * This file is distributed under GPLv2, please see
 * COPYING for more details.
 *
 * $Id$
 */
#include "clientaction.h"
#include "clientconnection.h"
#include "messageblock.h"
#include "message.h"
#include "logger.h"
#include "server.h"
#include "misc.h"
#include "permissions.h"
#include <memory>

using namespace std;

map<string, ClientAction::Info> ClientAction::_actionmap;
Queue<Message*> *ClientAction::_message_queue;

ClientAction::ClientAction() {
}

ClientAction::~ClientAction() {
}

bool ClientAction::registerAction(const string &action, const PermissionTest &pt, ClientAction *ca) {
	if(_actionmap.find(action) != _actionmap.end())
		log(LOG_WARNING, "Overriding action handler for action '%s'!", action.c_str());

	log(LOG_INFO, "Registering action '%s'", action.c_str());
	_actionmap[action] = Info(pt, ca);
	return true;
}

auto_ptr<MessageBlock> ClientAction::triggerMessage(ClientConnection *, Message *mb) {
	if(mb->makeMessage()) {
		sem_t sem;
		if (0 != sem_init(&sem, 0, 0)) {
			lerror("sem_init");
			_message_queue->enqueue(mb);
		} else {
			mb->setWatcher(&sem);
			_message_queue->enqueue(mb);
			sem_wait(&sem);
			sem_destroy(&sem);
		}
		return MessageBlock::ok();
	} else {
		delete mb;
		return MessageBlock::error("Internal error creating message.  This is indicative of a bug.");
	}
}

void ClientAction::process(ClientConnection *cc, const MessageBlock *mb) {
	auto_ptr<MessageBlock> reply;
	if(!Server::getId()) {
		reply = MessageBlock::error("Server has not yet been initialised - please try again later");
	}
	else
	{
		string action = mb->action();

		map<string, Info>::const_iterator it = _actionmap.find(action);
		if (it == _actionmap.end()) {
			uint32_t user_id = cc->getUserId();
			log(LOG_NOTICE, "Unknown action '%s' encountered on ClientConnection for user %u.", action.c_str(), user_id);
			reply = MessageBlock::error("No such action");
		}
		else if (!it->second.pt.matches(cc->permissions())) {
			uint32_t user_id = cc->getUserId();
			log(LOG_NOTICE, "Denied action '%s' for user %u.", action.c_str(), user_id);
			reply = MessageBlock::error("Action not permitted");
		}
		else {
			reply = it->second.action->int_process(cc, mb);
		}
	}
	if (reply.get() == NULL) {
		reply = MessageBlock::error("Internal error - no reply generated by " + mb->action());
	}
	reply->setMessageId(mb->getMessageId());
	cc->sendMessageBlock(reply.get());
}

void ClientAction::setMessageQueue(Queue<Message*> *message_queue) {
	_message_queue = message_queue;
}
